export { getAuthData } from './model/services/getAuthData/getAuthData';
export { useJsonSettings } from './model/selectors/getJsonSettings/getJsonSettings';
export { saveJsonSettings } from './model/services/setJsonSettings/saveJsonSettings';
export { useJsonSettingsByKey } from './model/selectors/getJsonSettings/getJsonSettings';
export { isAdminRole, isManagerRole, getRoles } from './model/selectors/IsAdminRole/IsAdminRole';
export { getUserInited } from './model/selectors/getUserInited/getUserInited';
export { getUserAuthData } from './model/selectors/getUserAuthData/getUserAuthData';
export { userReducer, userActions, useUserActions } from './model/slice/userSlice';
export { Role } from './model/types/user';
export type { User, UserSchema } from './model/types/user';
